### ISSUE TITLE
Plot failure with large number of parameters

### ISSUE THREAD

**Issue by johnveitch** [mj-will/nessai#280]
**Describe the bug**

Trace plot causes crash with the error `ValueError: Image size of 1200x69120 pixels is too large. It must be less than 2^16 in each direction.`

**To Reproduce**
I have 92 parameters. I would imagine trying a 100-D gaussian would reproduce.

**Expected behaviour**
No crash. If it's not possible to plot then catch the exception?

**Screenshots**
```
Traceback (most recent call last):
  File "/home/john/work/students/ann/fast_tutorial_mylikelihood.py", line 303, in <module>
    result = bilby.run_sampler(
  File "/home/john/src/bilby/bilby/core/sampler/__init__.py", line 234, in run_sampler
    result = sampler.run_sampler()
  File "/home/john/src/bilby/bilby/core/sampler/base_sampler.py", line 97, in wrapped
    output = method(self, *args, **kwargs)
  File "/home/john/src/bilby/bilby/core/sampler/nessai.py", line 247, in run_sampler
    self.fs.run(**run_kwargs)
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/nessai/flowsampler.py", line 240, in run
    self.logZ, self.nested_samples = self.ns.nested_sampling_loop()
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/nessai/samplers/nestedsampler.py", line 1249, in nested_sampling_loop
    self.update_state()
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/nessai/samplers/nestedsampler.py", line 1163, in update_state
    self.plot_trace(
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/nessai/samplers/nestedsampler.py", line 1094, in plot_trace
    fig = plot_trace(
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/nessai/plot.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/nessai/plot.py", line 501, in plot_trace
    fig.savefig(filename, bbox_inches="tight")
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/figure.py", line 3285, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2308, in print_figure
    renderer = _get_renderer(
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1559, in _get_renderer
    print_method(io.BytesIO())
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 517, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 463, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 399, in draw
    self.renderer = self.get_renderer()
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 384, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 416, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/home/john/.conda/envs/ann_msci/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 84, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 1200x69120 pixels is too large. It must be less than 2^16 in each direction.
````

**Additional context**

**Comment by mj-will** [comment]
@johnveitch thanks for reporting this. It would be good to address this before we release 0.8.0, so I'll aim to get a fix into a new beta release.

About the issue itself, I wonder if this could be caused by using the pixel marker `,`? E.g. it adds a pixel for every single point?
